.PHONY: all build setup_extension copy_files

# Define the path to the Chrome extension directory relative to the Makefile
EXT_DIR := ./chrome_extension

# Target that groups the build and setup tasks
all: build setup_extension

# Build the Rust project to WebAssembly
build:
	cargo build --target wasm32-unknown-unknown
	wasm-pack build --target web

# Setup the Chrome extension directory and copy necessary files
# Setup the Chrome extension directory and copy necessary files
setup_extension: copy_files
	@# Create the Chrome extension directory if it doesn't exist
	@mkdir -p $(EXT_DIR)
	@# Copy the manifest, background script, and popup html from the static directory to the extension directory
	cp static/manifest.json $(EXT_DIR)/manifest.json
	cp static/background.js $(EXT_DIR)/background.js
	cp static/popup.html $(EXT_DIR)/popup.html
	@# Copy the pkg directory generated by wasm-pack
	cp -r ./pkg $(EXT_DIR)

# Helper target for copying files
copy_files:
	@echo "Copying files to the Chrome extension directory..."
